language: python
python:
  - "2.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install pipenv
  - pipenv --version
  - pipenv install
  - pipenv install --dev
script: pipenv run py.test tests --cov-report term-missing --cov pypac
after_success:
  - coveralls
